name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  apply_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=v-backend-s3" -backend-config="dynamodb_table=v-backend-db" -backend-config="region=us-east-1"

      - name: Apply infrastructure
        run: terraform apply -auto-approve
